matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quantstack/manylinux_2010_x86_64-python-dev:latest
           PLAT=manylinux2010_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-wheels.sh
  - ls dist/
