name: Build Wheel

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}


jobs:
  osx:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: [3.7, 3.8, 3.9]

    env:
      CXX: clang++
      CC: clang

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '10.3'

    - name: Build wheel
      run: |
        export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
        bash ./scripts/build-osx-wheel.sh

    - uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse/xeus_python*.whl

  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    env:
      DOCKER_IMAGE: quay.io/pypa/manylinux2010_x86_64
      PLAT: manylinux2010_x86_64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pull docker image
      run: docker pull $DOCKER_IMAGE

    - name: Build wheel
      run: docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/scripts/build-wheels.sh

    - uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse/xeus_python*.whl
